theme: jekyll-theme-merlot
title: Ulaş Diyar Önder's Progress Journal
[hw1] (https://github.com/BU-IE-360/spring24-UlasDiyarOnder/tree/main/IE_360_HW1_2020402069)
description: This journal is created for IE 360 Spring24.
